### ISSUE TITLE
NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by LazizEx** [ExtCore/ExtCore-Sample-Data#1]
Здравствуйте.
Не как не могу решить эту проблему.
Мои действие:
1. Скачал "ExtCore-Sample-Data" с репозитории.
2. Компилировал решение.
3. Создал каталог "Extensions" в директории "WebApplication".
4. Положил туда "Extension.dll", "Extension.Data.Entities.dll" и "Extension.Data.Abstractions.dll".
5. Отредактировал файл "appsettings.json" 
`{
  "ConnectionStrings": {
    "Default": "Data Source=db.sqlite"
  },
  "Extensions": {
    "Path": "/Extensions"
  }
}`
на 
`{
  "ConnectionStrings": {
    "Default": "Data Source=db.sqlite"
  },
  "Extensions": {
    "Path": "\\Extensions"
  }
}`
по скольку у меня виндовс.

Запускаю... Ошибка! 
https://screenshots.firefox.com/bpxXGSt4SsKtN94r/localhost

Что не так?
Предполагаю, не может найти базу но, везде где можно сунул базу. Не помогло. 

Еще маленький вопрос. Можно ли отладить Екстенсионы?

**Comment by DmitrySikorsky** [comment]
Добрый день! По отладке. Да, конечно можно. Вот тут написал: http://docs.extcore.net/en/latest/fundamentals/debugging.html

По ошибке. Посмотрите, пожалуйста, вот этот пример: http://extcore.net/files/ExtCore-Sample-3.1.0.zip

Он 100% рабочий из коробки, можно сравнить. Думаю, в дебаге будет легко понять, в чем дело. Но раз у вас в контроллере null reference, скорее всего там IStorage = null, или же репозиторий = null. Возможно, вы не подключили сборку с имплементацией ExtCore.Data для конкретной СУБД.

**Comment by LazizEx** [comment]
Спасибо Дмитрий.
Нашел свою ошибку. Я дурак) забыл положить в папку "Extensions"еще и "Extension.Data.EntityFramework.Sqlite.dll".
Все прекрасно работает.

Я поражен Вашим умением, особенно понравился проект https://github.com/Platformus/Platformus, надеюсь не бросите проект. Я бы хотел помочь в этом проекте но, у меня не хватает опыта (или я в себе сомневаюсь).

**Comment by DmitrySikorsky** [comment]
После таких слов хочется с двойным упорством заниматься проектами :)
