### ISSUE TITLE
Is there possibility to link data between extensions?

### ISSUE THREAD

**Issue by DmitrijOkeanij** [ExtCore/ExtCore-Sample-Data#2]
If Person is like this, trying to understand how to write such code?

```
class Person : IEntity {
   public int Id { get; set; }
   public int Name { get; set; }
   public int PasportId { get;set;}
   public int Pasport { get;set; }
}

```
If Pasport is in main program or other module?

Or I just need to import Passport assemby here, and all is done?

**Comment by DmitrySikorsky** [comment]
Hi! If your Person entity needs to have a property of type Passport, its extension must have an explicit dependency on the extension (assembly) where it is defined. It is logical, that one extension depends on another one. So later in order to use your extension application will have to load another one too.

The same way it is done in my Platformus project. There is the Globalization extension, and all the extensions that needs to have localized content, must have dependencies on that Globalization extension.

**Comment by DmitrijOkeanij** [comment]
Да, я понимаю, на уровне логики. Но я хотел спросить, сработает ли всё это вместе именно в данном случае.

То есть я делаю модуль, в нём делаю reference на другой модуль и использую внутри первого ссылки на второй внутри entity, и всё работает, я правильно понимаю?

Жаль чуть раньше не нашёл ваш проект, а то целую неделю уже пытался сделать для своего проекта самостоятельно, но это оказалось не так просто... Хотя думаю что не жаль, а так надо было )) Ничего не происходит просто так.

**Comment by DmitrySikorsky** [comment]
Yes, it will work with no problems: https://github.com/Platformus/Platformus/blob/master/src/Platformus.Menus.Data.Entities/MenuItem.cs#L47

Dictionary type is defined here: https://github.com/Platformus/Platformus/blob/master/src/Platformus.Globalization.Data.Entities/Dictionary.cs

I'll be happy if my project help you.

**Comment by Dmitrij-Polyanin** [comment]
А правильно ли я понимаю, что если я в расширениях хочу использовать репозитории из основного проекта, то в основном проекте я должен делать такую же структуру, как в расширениях. То есть отдельные проекты под модель и абстракцию, и всё как у вас описано для расширений?

То есть у меня будет
MainSite.Data.Entities
и
MainSite.Data.Abstractions?

И тогда я в экстеншене смогу использовать эти репозитории из основной части проекта?

**Comment by Dmitrij-Polyanin** [comment]
И второй вопрос. что-то я не пойму, в вашем примере в экстеншене нет реализации репозитория, только определение интерфейса IPersonRepository

Я так понимаю что реализация делается как-то автоматически инфраструктурой ExtCore?

А как мне добавить свои методы и реализации их, например добавление Person и так далее, со своей кастомной логикой? И в каком проекте делать эти реализации, в MainSite.Data.Abstractions?
Просто я так понял из названия этого проекта, что он для интерфейсов.

Может быть стоит сделать пошире пример, что бы классы модели были и в основном сайте, и экстеншн их использовал у себя. И так же что бы были какие-то кастомные действия у репозитория?

**Comment by DmitrySikorsky** [comment]
I'm closing this issue for now. Feel free to reopen it any moment if you have any additional questions.
